services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

  rag:
    build:
      context: ./rag
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_LLM_MODEL: mistral
      OLLAMA_EMBED_MODEL: mxbai-embed-large
    volumes:
      - ./rag:/app
      - rag_data:/chroma
    ports:
      - "8001:8001"
    depends_on:
      - db
      - ollama


  app:
    build:
      context: ./streamlit
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword
      RAG_BASE_URL: http://rag:8001
    volumes:
      - ./streamlit:/app
      - ./streamlit/.streamlit:/root/.streamlit
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - rag
      - db

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  mysql_data:
  rag_data:
  ollama_data:
